apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "retailcode-mtn.portal.name" . }}
  name:  {{ include "retailcode-mtn.portal.name" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  {{ include "retailcode-mtn.portal.name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxUnavailable: 50%
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: {{ include "retailcode-mtn.portal.name" .}}
    spec:
      containers:
      - image: "{{ .Values.portal.image.repository }}"
        name: {{ include "retailcode-mtn.portal.name" .}}
        imagePullPolicy:  {{ .Values.portal.image.pullPolicy }}
        ports:
          - name: web
            containerPort: {{ .Values.portal.service.targetPort}}
        {{- if .Values.portal.resources.enable }}
        resources:
          requests:
            cpu: {{ .Values.portal.resources.requests.cpu }}
            memory: {{ .Values.portal.resources.requests.memory }}
          limits:
            cpu: {{ .Values.portal.resources.limits.cpu }}
            memory: {{ .Values.portal.resources.limits.memory }}
        {{- end }}
        securityContext:
        {{ if or (eq .Values.namespace "retcodedev") (eq .Values.namespace "retcodeprod")}}
            privileged: {{ .Values.securityContext.privileged }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            capabilities:
              drop:
                - "ALL"
            seccompProfile:
              type: {{ .Values.securityContext.seccompProfile.type }}
        {{ else }}
          privileged: false
        {{- end }}