apiVersion: v1
kind: Service
metadata:
  name: {{ include "retailcode-mtn.portal.name" .}}
  labels:
    app: {{ include "retailcode-mtn.portal.name" .}}
spec:
  selector:
    app: {{ include "retailcode-mtn.portal.name" .}}
  ports:
    - protocol: TCP
      name: {{ .Values.portal.service.name }}
      port: {{ .Values.portal.service.port }}
  type: {{ .Values.portal.service.type }}
