{{- if (eq .Values.namespace "retcodedev") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "retailcode-mtn.ussdgateway.name" . }}-ingress
spec:
  rules:
  - host: retailcode-mtn-ussdgateway.retailcode.africa
    http:
      paths:
      - pathType: ImplementationSpecific 
        backend:
          service:
            name: {{ include "retailcode-mtn.ussdgateway.name" . }}
            port:
              number: {{ .Values.ussdgateway.service.port }}
{{- end }}
