apiVersion: v1
kind: Service
metadata:
  name: {{ include "retailcode-mtn.ussdgateway.name" . }}
  annotations:
    metallb.universe.tf/address-pool: retcode
  labels:
    app: {{ include "retailcode-mtn.ussdgateway.name" . }}
spec:
  selector:
    app: {{ include "retailcode-mtn.ussdgateway.name" . }}
  ports:
    - protocol: TCP
      name: {{ .Values.ussdgateway.service.name }}
      port: {{ .Values.ussdgateway.service.port }}
  type: {{ .Values.ussdgateway.service.type }}
  loadBalancerIP: 10.184.52.231
